
CatchingErrors begin
    ref(InBytefile) bf;

    procedure onError(mess); text mess; begin
        outtext("Inside onError: " & mess); outimage;
        --bf.inbyte;
        goto LAB;
    end;
    
    procedure P; begin
        procedure Q; begin
            integer i;
            
            CatchingErrors begin
                procedure onError(mess); text mess; begin
                    outtext("DEEP Inside onError: " & mess); outimage;
                    goto LAB2;
                    --bf.inbyte;
                    --error("DEEP INSIDE AND CALLING ERROR");
                    --terminate_program;
                end;
                bf.inbyte;
            end;
            outtext("AFTER CALL ON ERROR"); outimage;
        end;
        Q;
    end;

    integer procedure safe_Getint(t); text t; begin
        CatchingErrors begin
            procedure onError(message); text message; begin
                safe_Getint:=maxint;
            end;
            safe_Getint:=t.getint;
        end;
    end;    

    outtext("Inside CatchingErrors"); outimage;

    outtext("safe_Getint=" & edit(safe_Getint("9999999999999"))); outimage;
    
    bf:-new InBytefile("TEST");
    bf.inbyte;
    
    outtext("CALL ON ERROR"); outimage;
    
    LAB:
    outtext("At LAB in CatchingErrors"); outimage;
    P;
    
    LAB2:
    outtext("At LAB2 in CatchingErrors"); outimage;

end;  